version: '3'

services:
 kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=alura_kafka_cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=127.0.0.1:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=127.0.0.1:2181