version: '3'

services:
  zookeeper:
    image: bitnami/zookeeper:3.8.1
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper_data:/bitnami/zookeeper/data
      - zookeeper_logs:/bitnami/zookeeper/logs

  kafka:
    image: bitnami/kafka:2.8.1
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_data:/bitnami/kafka/data
      - kafka_logs:/bitnami/kafka/logs

volumes:
  zookeeper_data:
    driver: local
  zookeeper_logs:
    driver: local
  kafka_data:
    driver: local
  kafka_logs:
    driver: local